services:
  ll_data:
    image: postgres:15
    container_name: ll_data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - .docker/volumes/sql_data:/var/lib/postgresql/data    
    networks:
      - bridge_net

  ll_api:
      image: 677276107921.dkr.ecr.eu-west-2.amazonaws.com/ll_api:1.0.0.0
      container_name: ll_api
      networks:
        - bridge_net
      depends_on:
        - ll_data
      env_file:
        - .env.dev
      ports:
      - "5197:5000"

  deepseek:
    image: docker.io/ollama/ollama
    container_name: deepseek
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: all
    volumes:
      - ~/.docker/volumes/ollama_data:/root/.ollama
    networks:
      - bridge_net
    restart: unless-stopped

  ll_webui :
    image: 677276107921.dkr.ecr.eu-west-2.amazonaws.com/ll_webui 
    container_name: ll_webui
    networks:
      - bridge_net
    depends_on:
      - ll_api 
    ports:
      - "3000:3000" 

networks:
  bridge_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1
